# Generated by Django 4.1.3 on 2023-02-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
