# Generated by Django 4.1.6 on 2023-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='comment',
            name='lop',
            field=models.CharField(default=0, max_length=50, verbose_name='Атор:'),
        ),
    ]
