# Generated by Django 4.1.6 on 2023-05-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0004_delete_photo_alter_comment_options_comment_lop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name="Ім'я:")),
                ('month', models.CharField(choices=[('value1', 'Січень'), ('value2', 'Лютий')], max_length=100, verbose_name='Місяць:')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lop',
        ),
    ]
