# Generated by Django 4.1.6 on 2023-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0005_application_alter_comment_options_remove_comment_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='arrival_country',
            field=models.CharField(default='', max_length=50, verbose_name='Куди:'),
        ),
        migrations.AddField(
            model_name='application',
            name='departure_city',
            field=models.CharField(default='', max_length=50, verbose_name='Місто:'),
        ),
        migrations.AddField(
            model_name='application',
            name='departure_country',
            field=models.CharField(default='', max_length=50, verbose_name='Звідки:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='month',
            field=models.CharField(choices=[('value1', 'Січень'), ('value2', 'Лютий')], max_length=50, verbose_name='Місяць:'),
        ),
    ]
