# Generated by Django 4.1.6 on 2023-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0008_rename_arrival_country_application_arrival_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='application',
            name='arrival',
            field=models.CharField(choices=[('0', 'Україна'), ('', ''), ('', ''), ('00', 'Польща'), ('', '')], max_length=50, verbose_name='Куди:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='departure',
            field=models.CharField(choices=[('0', 'Україна'), ('', ''), ('', ''), ('00', 'Польща'), ('', '')], max_length=50, verbose_name='Звідки:'),
        ),
    ]
