# Generated by Django 4.1.6 on 2023-05-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0009_rename_author_comment_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='author',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='author',
        ),
    ]
