# Generated by Django 4.1.6 on 2023-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0010_rename_author_application_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер телефону'),
        ),
    ]
