# Generated by Django 4.1.6 on 2023-05-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0012_alter_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='arrival',
            field=models.CharField(choices=[('0', 'Україна'), ('1', 'Тернопіль'), ('2', 'Львів'), ('00', 'Польща'), ('01', 'Каліш')], max_length=50, verbose_name='Куди:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='departure',
            field=models.CharField(choices=[('0', 'Україна'), ('1', 'Тернопіль'), ('2', 'Львів'), ('00', 'Польща'), ('01', 'Каліш')], max_length=50, verbose_name='Звідки:'),
        ),
    ]
